# travis file
# https://docs.travis-ci.com/user/customizing-the-build

notifications:
  email: false

branches:
  except:
    - l10n_master

language: node_js

node_js:
  - 10.1.0

env:
  - CXX=g++-4.8 NODE_ENV=production

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  directories:
    - node_modules

services:
  - mongodb
  - redis-server

before_script:
  - npm install

  # 設定ファイルを配置
  - cp ./.travis/default.yml ./.config
  - cp ./.travis/test.yml ./.config

  - travis_wait npm run build
