# travis file
# https://docs.travis-ci.com/user/customizing-the-build

notifications:
  email: false

language: node_js

node_js:
  - 9.8.0

env:
  - CXX=g++-4.8 NODE_ENV=production

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - graphicsmagick

cache:
  directories:
    # パッケージをキャッシュすると本来は動かないはずなのに動いてしまう
    # 場合があり危険なのでキャッシュはしない:
    #- node_modules

services:
  - mongodb
  - redis-server

before_script:
  # Travisはproduction環境なので(10行目により)、
  # npm install しただけでは devDependencies はインストールされないので、
  # --only=dev オプションを付けてそれらもインストールされるようにする:
  - npm install --only=dev

  # 設定ファイルを配置
  - cp ./.travis/default.yml ./.config
  - cp ./.travis/test.yml ./.config

  - travis_wait npm run build
