yarnPath: ".yarn/releases/yarn-berry.cjs"
httpTimeout: 600000

nmHoistingLimits: none

nodeLinker: pnpm

packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": npm:ansi-styles@6.1.0
      "#supports-color": npm:supports-color@9.2.2
  "@bull-board/api@*":
    peerDependencies:
      "@bull-board/ui": "*"
  chartjs-adapter-date-fns@*:
    peerDependencies:
      date-fns: "*"
  swiper@*:
    peerDependencies:
      vue: "*"
  consolidate@*:
    dependencies:
      ejs: "*"
  koa-views@*:
    dependencies:
      pug: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

progressBarStyle: patrick
