httpTimeout: 600000

nmHoistingLimits: none

nodeLinker: pnpm

packageExtensions:
  "@bull-board/api@*":
    peerDependencies:
      "@bull-board/ui": "*"
  chartjs-adapter-date-fns@*:
    peerDependencies:
      date-fns: "*"
  swiper@*:
    peerDependencies:
      vue: "*"
  consolidate@*:
    dependencies:
      ejs: "*"
  koa-views@*:
    dependencies:
      pug: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

progressBarStyle: patrick
