/**
 * @packageDocumentation
 *
 * API のパーミッション種別（read:account, write:notes 等）の一覧。
 *
 * @remarks
 * 種別を追加した場合は、翻訳（_permissions 以下）も必ず追加すること。
 *
 * @internal
 */
export const kinds = [
	"read:account",
	"write:account",
	"read:blocks",
	"write:blocks",
	"read:drive",
	"write:drive",
	"read:favorites",
	"write:favorites",
	"read:following",
	"write:following",
	"read:messaging",
	"write:messaging",
	"read:mutes",
	"write:mutes",
	"write:notes",
	"read:notifications",
	"write:notifications",
	"read:reactions",
	"write:reactions",
	"write:votes",
	"read:pages",
	"write:pages",
	"write:page-likes",
	"read:page-likes",
	"read:user-groups",
	"write:user-groups",
	"read:channels",
	"write:channels",
	"read:gallery",
	"write:gallery",
	"read:gallery-likes",
	"write:gallery-likes",
	"write:report-abuse",
	"read:federation",
	"read:categories",
	"write:categories",

	// 管理・モデレーション用。エンドポイント側の requireModerator /
	// requireAdmin は別途効くため、これらを付与しても権限が昇格することはない。
	"read:admin:abuse-user-reports",
	"read:admin:ad",
	"read:admin:announcements",
	"read:admin:drive",
	"read:admin:emoji",
	"read:admin:index-stats",
	"read:admin:meta",
	"read:admin:performance",
	"read:admin:queue",
	"read:admin:relays",
	"read:admin:server-info",
	"read:admin:show-moderation-log",
	"read:admin:show-user",
	"read:admin:support",
	"read:admin:table-stats",
	"read:admin:user-ips",
	"write:admin:account",
	"write:admin:ad",
	"write:admin:announcements",
	"write:admin:delete-account",
	"write:admin:delete-all-files-of-a-user",
	"write:admin:drive",
	"write:admin:emoji",
	"write:admin:federation",
	"write:admin:invite-codes",
	"write:admin:maintenance",
	"write:admin:meta",
	"write:admin:performance",
	"write:admin:promo",
	"write:admin:queue",
	"write:admin:relays",
	"write:admin:reset-password",
	"write:admin:resolve-abuse-user-report",
	"write:admin:roles",
	"write:admin:send-email",
	"write:admin:support",
	"write:admin:suspend-user",
	"write:admin:unsuspend-user",
	"write:admin:user-note",
];
