pipeline:
  testCommit:
    image: node:latest
    commands:
      - cp .config/ci.yml .config/default.yml
      - corepack enable
      - yarn set version berry
      - yarn install --immutable
      - yarn run build
      - yarn migrate

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=test
  redis:
    image: redis

branches:
  include: [ main, develop, feature/* ]
