pipeline:
  docker-build:
    image: plugins/kaniko
    settings:
      repo: thatonecalculator/calckey
      tags: test
      dockerfile: Dockerfile
      no_push: true
    when:
      event: commit

branches:
  include: [ master, develop ]
