pipeline:
  testCommit:
    image: node:latest
    commands:
      - cp .config/ci.yml .config/default.yml
      - npm i -g pnpm
      - pnpm i --frozen-lockfile
      - pnpm run build
      - pnpm run migrate

services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=test
  redis:
    image: redis

branches:
  include: [ main, develop, feature/* ]
