export const MFM_TAGS = [
	"tada",
	"jelly",
	"twitch",
	"shake",
	"spin",
	"jump",
	"bounce",
	"flip",
	"x2",
	"x3",
	"x4",
	"scale",
	"position",
	"fg",
	"bg",
	"font",
	"blur",
	"rainbow",
	"sparkle",
	"rotate",
];
export const MFM_TAGS_JP = [
	{name:"x2", ja:"サイズ2倍", exportLeft:"$[x2 ", exportRight:"]",},
	{name:"x3", ja:"サイズ3倍", exportLeft:"$[x3 ", exportRight:"]",},
	{name:"x4", ja:"サイズ4倍", exportLeft:"$[x4 ", exportRight:"]",},
	{name:"bold", ja:"太字", exportLeft:"**", exportRight:"**",},
	{name:"italic", ja:"斜体", exportLeft:"<i>", exportRight:"</i>",},
	{name:"strike", ja:"取り消し線", exportLeft:"~~", exportRight:"~~",},
	{name:"center", ja:"中央揃え", exportLeft:"<center>", exportRight:"</center>",},
	{name:"rainbow", ja:"ゲーミング", exportLeft:"$[rainbow ", exportRight:"]", defaultOption:"$[rainbow.speed=2s ",},
	{name:"sparkle", ja:"キラキラ", exportLeft:"$[sparkle ", exportRight:"]",},
	{name:"tada", ja:"じゃーん", exportLeft:"$[tada ", exportRight:"]", defaultOption:"$[tada.speed=1s ",},
	{name:"jelly", ja:"びよーん", exportLeft:"$[jelly ", exportRight:"]", defaultOption:"$[jelly.speed=1s ",},
	{name:"shake", ja:"振動（小）", exportLeft:"$[shake ", exportRight:"]", defaultOption:"$[shake.speed=0.5s ",},
	{name:"twitch", ja:"振動（大）", exportLeft:"$[twitch ", exportRight:"]", defaultOption:"$[twitch.speed=0.5s ",},
	{name:"jump", ja:"ジャンプ", exportLeft:"$[jump ", exportRight:"]", defaultOption:"$[jump.speed=0.75s ",},
	{name:"bounce", ja:"バウンド", exportLeft:"$[bounce ", exportRight:"]", defaultOption:"$[bounce.speed=0.75s ",},
	{name:"spin", ja:"右回転", exportLeft:"$[spin ", exportRight:"]", defaultOption:"$[spin.speed=1.5s ",},
	{name:"spin-l", ja:"左回転", exportLeft:"$[spin.left ", exportRight:"]", defaultOption:"$[spin.left,speed=1.5s ",},
	{name:"spin-a", ja:"往復回転", exportLeft:"$[spin.alternate ", exportRight:"]", defaultOption:"$[spin.alternate,speed=1.5s ",},
	{name:"spin-x", ja:"X回転", exportLeft:"$[spin.x ", exportRight:"]", defaultOption:"$[spin.x,speed=1.5s ",},
	{name:"spin-y", ja:"Y回転", exportLeft:"$[spin.y ", exportRight:"]", defaultOption:"$[spin.y,speed=1.5s ",},
	{name:"flip-h", ja:"横反転", exportLeft:"$[flip ", exportRight:"]",},
	{name:"flip-v", ja:"縦反転", exportLeft:"$[flip.v ", exportRight:"]",},
	{name:"flip-hv", ja:"縦横反転", exportLeft:"$[flip.h,v ", exportRight:"]",},
	{name:"blur", ja:"ぼかし", exportLeft:"$[blur ", exportRight:"]",},
	{name:"search", ja:"検索欄", exportLeft:"", exportRight:" [Search]",},
	{name:"serif", ja:"セリフフォント", exportLeft:"$[font.serif ", exportRight:"]",},
	{name:"mono", ja:"等幅フォント", exportLeft:"$[font.monospace ", exportRight:"]",},
	{name:"cursive", ja:"筆記体", exportLeft:"$[font.cursive ", exportRight:"]",},
	{name:"fantasy", ja:"ファンタジー", exportLeft:"$[font.fantasy ", exportRight:"]",},
	{name:"emoji", ja:"絵文字フォント", exportLeft:"$[font.emoji ", exportRight:"]",},
	{name:"math", ja:"計算式フォント", exportLeft:"$[font.math ", exportRight:"]",},
	{name:"plain", ja:"素で表示", exportLeft:"<plain>", exportRight:"</plain>",},
	{name:"small", ja:"控えめ", exportLeft:"<small>", exportRight:"</small>",},
	{name:"quote", ja:"引用", exportLeft:"> ", exportRight:"",},
	{name:"code", ja:"コード（行）", exportLeft:"`", exportRight:"`",},
	{name:"code-b", ja:"コードブロック", exportLeft:"```\n", exportRight:"\n```",},
	{name:"KaTeX", ja:"数式（行）", exportLeft:"\\(", exportRight:"\\)",},
	{name:"KaTeX-b", ja:"数式ブロック", exportLeft:"\\[", exportRight:"\\]",},
	{name:"fg", ja:"文字色変更", exportLeft:"$[fg ", exportRight:"]", defaultOption:"$[fg.color=FF0000 ",},
	{name:"bg", ja:"背景色変更", exportLeft:"$[bg ", exportRight:"]", defaultOption:"$[bg.color=FF0000 ",},
	{name:"scale", ja:"サイズ調整", exportLeft:"$[scale ", exportRight:"]", defaultOption:"$[scale.x=1,y=1 ",},
	{name:"position", ja:"位置調整", exportLeft:"$[position ", exportRight:"]", defaultOption:"$[position.x=0,y=0 ",},
	{name:"rotate", ja:"角度調整", exportLeft:"$[rotate ", exportRight:"]", defaultOption:"$[rotate.deg=90 ",},
	{name:"rotate-x", ja:"X角度調整", exportLeft:"$[rotate.x ", exportRight:"]", defaultOption:"$[rotate.x,deg=90 ",},
	{name:"rotate-y", ja:"Y角度調整", exportLeft:"$[rotate.y ", exportRight:"]", defaultOption:"$[rotate.y,deg=90 ",},
];