name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: 18.x
    - run: corepack enable
    - run: yarn set version 4.0.0-rc.6
    - run: yarn workspaces focus
    - run: yarn install --immutable
    - run: yarn workspaces foreach run lint

