name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'yarn'
        cache-dependency-path: |
          src/packages/backend/yarn.lock
          src/packages/client/yarn.lock
    - run: yarn install
    - run: yarn lint
