name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        workspace:
        - backend
        - client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: actions/setup-node@v3.2.0
      with:
        node-version: 18.x
    - run: corepack enable
    - run: yarn set version berry
    - run: yarn workspaces foreach install --immutable
      env:
        YARN_CHECKSUM_BEHAVIOR: update
    - run: yarn workspace ${{ matrix.workspace }} run lint
